# Generated by Django 4.2.23 on 2025-08-18 09:41

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathers_name', models.CharField(max_length=255, verbose_name='Όνομα Πατέρα')),
                ('am', models.CharField(max_length=20, unique=True, verbose_name='Αριθμός Μητρώου')),
                ('afm', models.CharField(max_length=20, unique=True, verbose_name='Αριθμός Φορολογικού Μητρώου')),
                ('hire_date', models.DateField(verbose_name='Ημερομηνία Πρόσληψης')),
                ('specialty', models.CharField(max_length=255, verbose_name='Ειδικότητα')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Τηλέφωνο')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='Κινητό')),
                ('is_hr', models.BooleanField(default=False, verbose_name='Υπάλληλος HR')),
                ('is_director', models.BooleanField(default=False, verbose_name='Διευθυντής')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Τύπος Άδειας')),
                ('max_days', models.IntegerField(verbose_name='Μέγιστες Ημέρες Άδειας')),
                ('max_months', models.IntegerField(default=0, help_text='Συμπληρώστε μόνο για μακροπρόθεσμες άδειες (μήνες).', verbose_name='Μέγιστοι Μήνες Άδειας')),
                ('is_long_term', models.BooleanField(default=False, verbose_name='Μακροπρόθεσμη Άδεια')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Οργανισμός')),
                ('address', models.TextField(blank=True, verbose_name='Διεύθυνση')),
                ('director_name', models.CharField(blank=True, max_length=255, verbose_name='Όνομα Διευθυντή')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email Επικοινωνίας')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Τηλέφωνο Επικοινωνίας')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Ημερομηνία Έναρξης')),
                ('end_date', models.DateField(verbose_name='Ημερομηνία Λήξης')),
                ('leave_days_count', models.IntegerField(verbose_name='Αριθμός Ημερών Άδειας')),
                ('reason', models.TextField(verbose_name='Αιτιολογία')),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Received', 'HR Received'), ('Awaiting_Documentation', 'Awaiting Employee Documentation'), ('Ready_for_Approval', 'Ready for Director Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Canceled', 'Canceled')], default='Submitted', max_length=50, verbose_name='Κατάσταση')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Λόγος Απόρριψης')),
                ('protocol_number', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Αριθμός Πρωτοκόλλου')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_management.employee', verbose_name='Υπάλληλος')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_management.leavetype', verbose_name='Τύπος Άδειας')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave_management.organization', verbose_name='Οργανισμός'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης'),
        ),
    ]
