# Generated by Django 4.2.23 on 2025-08-20 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0002_leaveapplication_leave_months_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leave_management.leavetype', verbose_name='Τύπος Άδειας'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='is_long_term',
            field=models.BooleanField(default=False, verbose_name='Μακροχρόνια Άδεια'),
        ),
    ]
